export const ALL_CUSTOM_ORDER_REQUEST = "ALL_CUSTOM_ORDER_REQUEST";
export const ALL_CUSTOM_ORDER_SUCCESS = "ALL_CUSTOM_ORDER_SUCCESS";
export const ALL_CUSTOM_ORDER_FAIL = "ALL_CUSTOM_ORDER_FAIL";

export const ADMIN_CUSTOM_ORDER_REQUEST = "ADMIN_CUSTOM_ORDER_REQUEST";
export const ADMIN_CUSTOM_ORDER_SUCCESS = "ADMIN_CUSTOM_ORDER_SUCCESS";
export const ADMIN_CUSTOM_ORDER_FAIL = "ADMIN_CUSTOM_ORDER_FAIL";

export const NEW_CUSTOM_ORDER_REQUEST = "NEW_CUSTOM_ORDER_REQUEST";
export const NEW_CUSTOM_ORDER_SUCCESS = "NEW_CUSTOM_ORDER_SUCCESS";
export const NEW_CUSTOM_ORDER_RESET = "NEW_CUSTOM_ORDER_RESET";
export const NEW_CUSTOM_ORDER_FAIL = "NEW_CUSTOM_ORDER_FAIL";

export const UPDATE_CUSTOM_ORDER_REQUEST = "UPDATE_CUSTOM_ORDER_REQUEST";
export const UPDATE_CUSTOM_ORDER_SUCCESS = "UPDATE_CUSTOM_ORDER_SUCCESS";
export const UPDATE_CUSTOM_ORDER_RESET = "UPDATE_CUSTOM_ORDER_RESET";
export const UPDATE_CUSTOM_ORDER_FAIL = "UPDATE_CUSTOM_ORDER_FAIL";

export const ASSIGN_CUSTOM_ORDER_REQUEST = "ASSIGN_CUSTOM_ORDER_REQUEST";
export const ASSIGN_CUSTOM_ORDER_SUCCESS = "ASSIGN_CUSTOM_ORDER_SUCCESS";
export const ASSIGN_CUSTOM_ORDER_FAIL = "ASSIGN_CUSTOM_ORDER_FAIL";
export const ASSIGN_CUSTOM_ORDER_RESET = "ASSIGN_CUSTOM_ORDER_RESET";

export const DELETE_CUSTOM_ORDER_REQUEST = "DELETE_CUSTOM_ORDER_REQUEST";
export const DELETE_CUSTOM_ORDER_SUCCESS = "DELETE_CUSTOM_ORDER_SUCCESS";
export const DELETE_CUSTOM_ORDER_RESET = "DELETE_CUSTOM_ORDER_RESET";
export const DELETE_CUSTOM_ORDER_FAIL = "DELETE_CUSTOM_ORDER_FAIL";

export const CUSTOM_ORDER_DETAILS_REQUEST = "CUSTOM_ORDER_DETAILS_REQUEST";
export const CUSTOM_ORDER_DETAILS_SUCCESS = "CUSTOM_ORDER_DETAILS_SUCCESS";
export const CUSTOM_ORDER_DETAILS_FAIL = "CUSTOM_ORDER_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const MY_CUSTOM_ORDERS_REQUEST = "MY_CUSTOM_ORDERS_REQUEST";
export const MY_CUSTOM_ORDERS_SUCCESS = "MY_CUSTOM_ORDERS_SUCCESS";
export const MY_CUSTOM_ORDERS_FAIL = "MY_CUSTOM_ORDERS_FAIL";


export const CONFIRM_CUSTOM_ORDER_REQUEST = "CONFIRM_CUSTOM_ORDER_REQUEST";
export const CONFIRM_CUSTOM_ORDER_SUCCESS = "CONFIRM_CUSTOM_ORDER_SUCCESS";
export const CONFIRM_CUSTOM_ORDER_RESET = "CONFIRM_CUSTOM_ORDER_RESET";
export const CONFIRM_CUSTOM_ORDER_FAIL = "CONFIRM_CUSTOM_ORDER_FAIL";

export const DECLINE_CUSTOM_ORDER_REQUEST = "DECLINE_CUSTOM_ORDER_REQUEST";
export const DECLINE_CUSTOM_ORDER_SUCCESS = "DECLINE_CUSTOM_ORDER_SUCCESS";
export const DECLINE_CUSTOM_ORDER_RESET = "DECLINE_CUSTOM_ORDER_RESET";
export const DECLINE_CUSTOM_ORDER_FAIL = "DECLINE_CUSTOM_ORDER_FAIL";

export const PENDING_CUSTOM_ORDER_REQUEST = "ADMIN_CUSTOM_ORDER_REQUEST";
export const PENDING_CUSTOM_ORDER_SUCCESS = "ADMIN_CUSTOM_ORDER_SUCCESS";
export const PENDING_CUSTOM_ORDER_FAIL = "ADMIN_CUSTOM_ORDER_FAIL";

export const  CONFIRMED_CUSTOM_ORDER_REQUEST = "ADMIN_CUSTOM_ORDER_REQUEST";
export const  CONFIRMED_CUSTOM_ORDER_SUCCESS = "ADMIN_CUSTOM_ORDER_SUCCESS";
export const  CONFIRMED_CUSTOM_ORDER_FAIL = "ADMIN_CUSTOM_ORDER_FAIL";

export const ASSIGNED_CUSTOM_ORDER_REQUEST = "ADMIN_CUSTOM_ORDER_REQUEST";
export const ASSIGNED_CUSTOM_ORDER_SUCCESS = "ADMIN_CUSTOM_ORDER_SUCCESS";
export const ASSIGNED_CUSTOM_ORDER_FAIL = "ADMIN_CUSTOM_ORDER_FAIL";

export const ASSIGNED_TO_CUSTOM_ORDER_REQUEST = "ADMIN_CUSTOM_ORDER_REQUEST";
export const ASSIGNED_TO_CUSTOM_ORDER_SUCCESS = "ADMIN_CUSTOM_ORDER_SUCCESS";
export const ASSIGNED_TO_CUSTOM_ORDER_FAIL = "ADMIN_CUSTOM_ORDER_FAIL";

export const UPDATE_PROGRESS_REQUEST = "UPDATE_PROGRESS_REQUEST";
export const UPDATE_PROGRESS_SUCCESS = "UPDATE_PROGRESS_SUCCESS";
export const UPDATE_PROGRESS_FAIL    =    "UPDATE_PROGRESS_FAIL";
export const UPDATE_PROGRESS_RESET   =   "UPDATE_PROGRESS_RESET";

export const C_PENDING_TO_CUSTOM_ORDER_REQUEST = "ADMIN_CUSTOM_ORDER_REQUEST";
export const C_PENDING_TO_CUSTOM_ORDER_SUCCESS = "ADMIN_CUSTOM_ORDER_SUCCESS";
export const C_PENDING_TO_CUSTOM_ORDER_FAIL = "ADMIN_CUSTOM_ORDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
