// invoiceConstants.js
export const CREATE_INVOICE_REQUEST = "CREATE_INVOICE_REQUEST";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL";
export const CLEAR_INVOICE_ERRORS = "CLEAR_INVOICE_ERRORS";
